name: Run Dataform QA Guard

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 2 * * *'

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          skip_install: false
          version: latest

      - name: Execute Quality Monitoring Script
        env:
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          LOCATION: ${{ secrets.LOCATION }}
          REPOSITORY_ID: ${{ secrets.REPOSITORY_ID }}
          BIGQUERY_TABLE_ID: ${{ secrets.BIGQUERY_TABLE_ID }}
        run: |
          python src/main.py
